package inflation;

import static java.awt.Color.RED;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.InputMismatchException;
import java.util.TreeMap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LT EORexton
 * @version 1.2
 */
public class Menu extends javax.swing.JFrame {

    private static final HashMap<String, Double> CPI = new HashMap<>();
    private static TreeMap<String, Double> SORTEDCPI;
    
    Object [] keys;
    
    private static final double cpi[] = {0.52, 0.53, 0.57, 0.61, 0.67, 0.70, 0.72, 0.83, 0.85, 0.88, 0.89, 0.89, 0.89, 0.91, 0.94, 0.97, 1.00, 1.03, 1.05, 1.08, 1.11, 1.13, 1.22, 1.25, 1.32, 1.44, 1.68, 1.97, 2.17, 2.45, 2.76, 2.99, 3.37, 3.79, 4.64, 5.32, 5.80, 6.43, 7.11, 7.73, 8.68, 9.84, 11.4, 13.64, 17.36, 25.35, 32.65, 33.17, 36.15, 40.21, 42.85, 45.37, 49.89, 52.75, 53.79, 59.06, 66.03, 72.57, 76.95, 80.24, 92.36, 102.09, 106.26, 121.17, 132.53, 140.11, 149.75, 159.60, 169.68, 183.23
    };

    /**
     * Creates new form Menu
     */
    public Menu() {
        initMap();
        orderMap();
        getKeys();
        initComponents();

    }

    /*
     * The initializeMap() method maps a year to its CPI rate. 
     * Note that CPI values have been retrived from the Kenya National Bureau
     * of Statistics (KNBS)
     */
    private void initMap() {
        CPI.put("1948", 0.52);
        CPI.put("1949", 0.53);
        CPI.put("1950", 0.57);
        CPI.put("1951", 0.61);
        CPI.put("1952", 0.67);
        CPI.put("1953", 0.70);
        CPI.put("1954", 0.72);
        CPI.put("1955", 0.83);
        CPI.put("1956", 0.85);
        CPI.put("1957", 0.88);
        CPI.put("1958", 0.89);
        CPI.put("1959", 0.89);
        CPI.put("1960", 0.89);
        CPI.put("1961", 0.91);
        CPI.put("1962", 0.94);
        CPI.put("1963", 0.97);
        CPI.put("1964", 1.00);
        CPI.put("1965", 1.03);
        CPI.put("1966", 1.05);
        CPI.put("1967", 1.08);
        CPI.put("1968", 1.11);
        CPI.put("1969", 1.13);
        CPI.put("1970", 1.22);
        CPI.put("1971", 1.25);
        CPI.put("1972", 1.32);
        CPI.put("1973", 1.44);
        CPI.put("1974", 1.68);
        CPI.put("1975", 1.97);
        CPI.put("1976", 2.17);
        CPI.put("1977", 2.45);
        CPI.put("1978", 2.76);
        CPI.put("1979", 2.99);
        CPI.put("1980", 3.37);
        CPI.put("1981", 3.79);
        CPI.put("1982", 4.64);
        CPI.put("1983", 5.32);
        CPI.put("1984", 5.80);
        CPI.put("1985", 6.43);
        CPI.put("1986", 7.11);
        CPI.put("1987", 7.73);
        CPI.put("1988", 8.68);
        CPI.put("1989", 9.84);
        CPI.put("1990", 11.4);
        CPI.put("1991", 13.64);
        CPI.put("1992", 17.36);
        CPI.put("1993", 25.35);
        CPI.put("1994", 32.65);
        CPI.put("1995", 33.17);
        CPI.put("1996", 36.15);
        CPI.put("1997", 40.21);
        CPI.put("1998", 42.85);
        CPI.put("1999", 45.37);
        CPI.put("2000", 49.89);
        CPI.put("2001", 52.75);
        CPI.put("2002", 53.79);
        CPI.put("2003", 59.06);
        CPI.put("2004", 66.03);
        CPI.put("2005", 72.57);
        CPI.put("2006", 76.95);
        CPI.put("2007", 80.24);
        CPI.put("2008", 92.36);
        CPI.put("2009", 102.09);
        CPI.put("2010", 106.26);
        CPI.put("2011", 121.17);
        CPI.put("2012", 132.53);
        CPI.put("2013", 140.11);
        CPI.put("2014", 149.75);
        CPI.put("2015", 159.60);
        CPI.put("2016", 169.68);
        CPI.put("2017", 183.23);

    }
    
    private void orderMap(){
        SORTEDCPI=new TreeMap<>(CPI);
    }
    
    private void getKeys(){
        keys=SORTEDCPI.keySet().toArray();
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_result = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        txt_result = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_amount = new javax.swing.JTextField();
        lbl_enteramount = new javax.swing.JLabel();
        year_from = new javax.swing.JComboBox();
        year_to = new javax.swing.JComboBox();
        lbl_yearto = new javax.swing.JLabel();
        lbl_yearfrom = new javax.swing.JLabel();
        btn_findvalue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inflation Calculator");
        setMinimumSize(new java.awt.Dimension(399, 298));
        setResizable(false);
        setSize(new java.awt.Dimension(399, 298));

        lbl_result.setText("Result:");

        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_result, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_result, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_result, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_result, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_amount.setToolTipText("In Kenya Shillings");

        lbl_enteramount.setText("Enter Amount");
        lbl_enteramount.setToolTipText("In Kenya Shillings");

        year_from.setModel(new javax.swing.DefaultComboBoxModel(keys));
        year_from.setToolTipText("");
        year_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_fromActionPerformed(evt);
            }
        });

        year_to.setModel(new javax.swing.DefaultComboBoxModel(keys));
        year_to.setToolTipText("");
        year_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_toActionPerformed(evt);
            }
        });

        lbl_yearto.setText("Year to:");

        lbl_yearfrom.setText("Year from:");

        btn_findvalue.setText("FIND VALUE");
        btn_findvalue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_findvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findvalueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_yearto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_enteramount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_yearfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(year_from, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 99, Short.MAX_VALUE)))
                        .addGap(32, 32, 32)
                        .addComponent(year_to, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_findvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_enteramount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_yearto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_yearfrom, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(year_from, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_to, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btn_findvalue))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void year_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_fromActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_year_fromActionPerformed

    private void year_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_toActionPerformed

    private void btn_findvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findvalueActionPerformed
        // TODO add your handling code here:

        String yearfrom=year_from.getSelectedItem().toString();
        String yearto=year_to.getSelectedItem().toString();
        int selection1 = Integer.parseInt(yearfrom);
        int selection2 = Integer.parseInt(yearto);
        
        double amount = 0.0;
        
        try {

            amount = Double.parseDouble(txt_amount.getText());

            double result = 0;
            
            if(amount > 0){
                result=amount * (CPI.get(yearto)/CPI.get(yearfrom));
            }
            
            DecimalFormat df = new DecimalFormat(".00");

            txt_result.setText(df.format(result));

        } catch (InputMismatchException e) {
            lbl5.setForeground(RED);
            lbl5.setText("*NUMBERS ONLY! No text!*");
        } catch (NumberFormatException n) {
            lbl5.setForeground(RED);
            lbl5.setText("*NUMBERS ONLY!*");
        }
    }//GEN-LAST:event_btn_findvalueActionPerformed

    private void txt_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_findvalue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl_enteramount;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel lbl_yearfrom;
    private javax.swing.JLabel lbl_yearto;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_result;
    private javax.swing.JComboBox year_from;
    private javax.swing.JComboBox year_to;
    // End of variables declaration//GEN-END:variables
}
